### ISSUE TITLE
Method [check] does not exist.

### ISSUE THREAD

**Issue by DanieleSassoli** [irazasyed/jwt-auth-guard#21] opened 2016-04-12 10:09 UTC
Hi,
 I'm trying to authenticate my user, but when I try to retrieve the user's data, I get this error: 

> Method [check] does not exist.

this is my authentication code, which works perfectly.

`if (! $token = Auth::guard('companies')->attempt($credentials)) {
            return response()->json(['error' => 'invalid_credentials'], 401);
}`

then I try to retrieve the company like this: 

`$user = Auth::user()`

But I get `Method [check] does not exist.`, There is no check method in JwtAuthGuard.php, should I include JWTAuth somehow or is this just a problem with the library itself? 
If I remove `|| ! $this->jwt->check()` from JwtAuthGuard.php line 62, everything works fine.
Thanks.

**Comment by wemersonjanuario** [comment] 2016-04-12 18:22
I have the same problem. 
There is no check method in JWTAuth.php,

**Comment by irazasyed** [comment] 2016-04-12 18:56
Alright, Allow me sometime and I'll push fixes for all these issues. 

The problem is, The dependency package is quite unstable and always changing now and then. Hence, it keeps breaking this package as well.

**Comment by wemersonjanuario** [comment] 2016-04-12 19:01
it would a good idea you write the suggested tymondesigns/jwt-auth version to require to work correctly with your tag. To avoid dev-master

**Comment by irazasyed** [comment] 2016-04-12 20:03
@wemersonjanuario Yeah, Makes sense. I'll do that once I fix these issues and make sure things are working well.

**Comment by irazasyed** [comment] 2016-04-26 18:10
Fixed in last commit.

**Closed as completed by irazasyed** 2016-04-26 18:10 UTC
